// Code generated by qtc from "jaeger.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vlselect/jaeger/jaeger.qtpl:1
package jaeger

//line app/vlselect/jaeger/jaeger.qtpl:1
import (
	"sort"
)

//line app/vlselect/jaeger/jaeger.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vlselect/jaeger/jaeger.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vlselect/jaeger/jaeger.qtpl:7
func StreamGetServicesResponse(qw422016 *qt422016.Writer, serviceList []string) {
//line app/vlselect/jaeger/jaeger.qtpl:7
	qw422016.N().S(`{`)
//line app/vlselect/jaeger/jaeger.qtpl:10
	sort.Slice(serviceList, func(i, j int) bool { return serviceList[i] < serviceList[j] })

//line app/vlselect/jaeger/jaeger.qtpl:11
	qw422016.N().S(`"data":[`)
//line app/vlselect/jaeger/jaeger.qtpl:13
	if len(serviceList) > 0 {
//line app/vlselect/jaeger/jaeger.qtpl:14
		qw422016.N().S(serviceList[0])
//line app/vlselect/jaeger/jaeger.qtpl:15
		for _, service := range serviceList[1:] {
//line app/vlselect/jaeger/jaeger.qtpl:15
			qw422016.N().S(`,`)
//line app/vlselect/jaeger/jaeger.qtpl:16
			qw422016.N().S(service)
//line app/vlselect/jaeger/jaeger.qtpl:17
		}
//line app/vlselect/jaeger/jaeger.qtpl:18
	}
//line app/vlselect/jaeger/jaeger.qtpl:18
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line app/vlselect/jaeger/jaeger.qtpl:23
	qw422016.N().D(len(serviceList))
//line app/vlselect/jaeger/jaeger.qtpl:23
	qw422016.N().S(`,}`)
//line app/vlselect/jaeger/jaeger.qtpl:25
}

//line app/vlselect/jaeger/jaeger.qtpl:25
func WriteGetServicesResponse(qq422016 qtio422016.Writer, serviceList []string) {
//line app/vlselect/jaeger/jaeger.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/jaeger/jaeger.qtpl:25
	StreamGetServicesResponse(qw422016, serviceList)
//line app/vlselect/jaeger/jaeger.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/jaeger/jaeger.qtpl:25
}

//line app/vlselect/jaeger/jaeger.qtpl:25
func GetServicesResponse(serviceList []string) string {
//line app/vlselect/jaeger/jaeger.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/jaeger/jaeger.qtpl:25
	WriteGetServicesResponse(qb422016, serviceList)
//line app/vlselect/jaeger/jaeger.qtpl:25
	qs422016 := string(qb422016.B)
//line app/vlselect/jaeger/jaeger.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/jaeger/jaeger.qtpl:25
	return qs422016
//line app/vlselect/jaeger/jaeger.qtpl:25
}

//line app/vlselect/jaeger/jaeger.qtpl:27
func StreamGetOperationsResponse(qw422016 *qt422016.Writer, operationList []string) {
//line app/vlselect/jaeger/jaeger.qtpl:27
	qw422016.N().S(`{`)
//line app/vlselect/jaeger/jaeger.qtpl:30
	sort.Slice(operationList, func(i, j int) bool { return operationList[i] < operationList[j] })

//line app/vlselect/jaeger/jaeger.qtpl:31
	qw422016.N().S(`"data":[`)
//line app/vlselect/jaeger/jaeger.qtpl:33
	if len(operationList) > 0 {
//line app/vlselect/jaeger/jaeger.qtpl:34
		qw422016.N().S(operationList[0])
//line app/vlselect/jaeger/jaeger.qtpl:35
		for _, operation := range operationList[1:] {
//line app/vlselect/jaeger/jaeger.qtpl:35
			qw422016.N().S(`,`)
//line app/vlselect/jaeger/jaeger.qtpl:36
			qw422016.N().S(operation)
//line app/vlselect/jaeger/jaeger.qtpl:37
		}
//line app/vlselect/jaeger/jaeger.qtpl:38
	}
//line app/vlselect/jaeger/jaeger.qtpl:38
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line app/vlselect/jaeger/jaeger.qtpl:43
	qw422016.N().D(len(operationList))
//line app/vlselect/jaeger/jaeger.qtpl:43
	qw422016.N().S(`,}`)
//line app/vlselect/jaeger/jaeger.qtpl:45
}

//line app/vlselect/jaeger/jaeger.qtpl:45
func WriteGetOperationsResponse(qq422016 qtio422016.Writer, operationList []string) {
//line app/vlselect/jaeger/jaeger.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/jaeger/jaeger.qtpl:45
	StreamGetOperationsResponse(qw422016, operationList)
//line app/vlselect/jaeger/jaeger.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/jaeger/jaeger.qtpl:45
}

//line app/vlselect/jaeger/jaeger.qtpl:45
func GetOperationsResponse(operationList []string) string {
//line app/vlselect/jaeger/jaeger.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/jaeger/jaeger.qtpl:45
	WriteGetOperationsResponse(qb422016, operationList)
//line app/vlselect/jaeger/jaeger.qtpl:45
	qs422016 := string(qb422016.B)
//line app/vlselect/jaeger/jaeger.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/jaeger/jaeger.qtpl:45
	return qs422016
//line app/vlselect/jaeger/jaeger.qtpl:45
}
